apiVersion: 1

datasources:
  - name: room-temperature-poc
    type: postgres
    uid: dfmh9yr5kulfka
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: telemetry
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
